# This stuff currently lives in src/cms/cms.js
media_library:
  name: cloudinary
  config:
    cloud_name: dy6lb8vna
    api_key: 241846326259277
    # mulitple: true
media_folder: 'src/images'
public_folder: 'images'

backend:
  name: git-gateway
  branch: master

collections:
  - name: 'posts'
    label: 'Post'
    folder: 'src/posts'
    create: true
    slug: '{{slug}}'
    fields:
      - { label: 'URL Path example: /postName', name: 'slug', widget: 'string' }
      - { label: 'Publish Date', name: 'date', widget: 'datetime' }
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Content', name: 'body', widget: 'markdown' }
  - name: 'inventory'
    label: 'Current Inventory'
    folder: 'src/store'
    slug: '{{slug}}'
    create: true
    fields:
      - {
          label: 'URL Path example: /productName',
          name: 'slug',
          widget: 'string',
        }
      - { label: 'ID', name: 'id', widget: 'string' }
      - { label: 'Price', name: 'price', widget: 'number', valueType: 'int' }
      - { label: 'Image', name: 'image', widget: 'image' }
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Date Added', name: 'date', widget: 'datetime' }
      - { label: 'Description', name: 'body', widget: 'markdown' }
  - name: 'events'
    label: 'Upcoming Event'
    folder: 'src/events'
    create: true
    fields:
      - { label: 'Event Title', name: 'title', widget: 'string' }
      - { label: 'Event URL', name: 'url' }
      - { label: 'Date', name: 'date', widget: 'date' }
      - { label: 'Location', name: 'location', widget: 'string' }
