# This stuff currently lives in src/cms/cms.js
media_library:
  name: cloudinary
  config:
    cloud_name: dy6lb8vna
    api_key: 241846326259277
media_folder: 'src/images'
public_folder: 'images'

backend:
  name: git-gateway
  branch: master

collections:
  - name: 'posts'
    label: 'Post'
    folder: 'src/cms/posts'
    create: true
    slug: '{{slug}}'
    fields:
      - { label: 'URL Path example: /postName', name: 'slug', widget: 'string' }
      - { label: 'Publish Date', name: 'date', widget: 'datetime' }
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Content', name: 'body', widget: 'markdown' }
  - name: 'inventory'
    label: 'Current Inventory'
    folder: 'src/cms/store'
    slug: '{{slug}}'
    create: true
    fields:
      - { label: 'URL Path example: /productName', name: 'slug', widget: 'string' }
      - { label: 'ID', name: 'id', widget: 'string' }
      - { label: 'Price', name: 'price', widget: 'number', valueType: 'int' }
      - { label: 'Image', name: 'image', widget: 'image' }
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Date Added', name: 'date', widget: 'datetime' }
      - { label: 'Description', name: 'body', widget: 'markdown' }
  - name: 'events'
    label: 'Upcoming Event'
    folder: 'src/cms/events'
    create: true
    fields:
      - { label: 'Event Title', name: 'title', widget: 'string' }
      - { label: 'Event URL', name: 'url' }
      - { label: 'Date', name: 'date', widget: 'date' }
      - { label: 'Location', name: 'location', widget: 'string' }
   - name: 'pages'
     label: 'Page Content'
     files:
      - name: 'about'
        label: 'About Page'
        file: 'src/cms/about/about.md'
        fields:
          - { label: 'Title', name: 'title', widget: 'string' }
          - { label: 'About Page Text', name: 'body', widget: 'markdown' }
      - name: 'welcome'
        label: 'Home Page Welcome Message'
        file: 'src/cms/welcome/welcome.md'
        fields:
          - { label: 'Title', name: 'title', widget: 'string' }
          - { label: 'Welcome Message', name: 'body', widget: 'markdown' }
      - name: 'faq'
        label: 'FAQ'
        file: 'src/cms/faq/faq.md'
        fields:
          - { label: 'Title', name: 'title', widget: 'string' }
          - { label: 'FAQ Page', name: 'body', widget: 'markdown' }
      - name: 'store banner'
        label: 'Store Banner'
        file: 'src/cms/store-banner/store-banner.md'
        fields:
          - { label: 'Title', name: 'title', widget: 'string' }
          - { label: 'Store Banner', name: 'body', widget: 'markdown' }
